"""Generate a full review set — every platform, every pillar, real images.

    python tools/showcase.py                 the standard sweep
    python tools/showcase.py --quick         one pillar per platform
    python tools/showcase.py --pillars proof,timely

Writes everything to `output/showcase_<timestamp>/` with an `index.html` you can
open, so a human can judge the whole campaign at once rather than one Telegram
message at a time.

## It uses the real pipeline, not a demo path

Every post here goes through the same `post_system_prompt`, the same four
validators and the same renderer that a scheduled run uses. What you see is
exactly what would have published, which is the only version of this worth
looking at — a preview generated by a different code path proves nothing about
the code that actually posts.

Publishing is the single step that is skipped. Nothing reaches a real account,
no idempotency claim is taken, and no trend angle is consumed.
"""
from __future__ import annotations

import argparse
import html
import json
import shutil
import sys
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

AGENT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(AGENT_ROOT))

# What a reviewer actually needs to see: each platform in the format it really
# uses, across pillars that exercise different grounding paths.
#   proof/client_voice -> must cite a REAL project or testimonial
#   teach/pov/process  -> no external facts, pure voice
#   timely             -> external facts, must be source-grounded
SWEEP: list[tuple[str, str, str, int]] = [
    ("instagram", "proof", "carousel", 6),
    ("instagram", "teach", "carousel", 5),
    ("facebook", "process", "single", 0),
    ("facebook", "client_voice", "single", 0),
    ("threads", "pov", "text", 0),
    ("threads", "teach", "text", 0),
    ("linkedin", "proof", "carousel", 8),
    ("linkedin", "pov", "text", 0),
    ("pinterest", "proof", "pin", 0),
    ("x", "teach", "thread", 0),
    ("x", "pov", "thread", 0),
    # Timely exercises the whole trend path: a verified angle, its captured
    # sources through the grounding gate, and a citation bound for a first
    # comment. Skips cleanly when no angle is ready, which is honest rather
    # than a failure — most hours genuinely have nothing worth reacting to.
    ("threads", "timely", "text", 0),
    ("linkedin", "timely", "text", 0),
]
QUICK = [SWEEP[0], SWEEP[2], SWEEP[4], SWEEP[8], SWEEP[9]]


def build(config, cases: list, out_dir: Path) -> list[dict]:
    from wizcore.facts.site import SiteReader
    from wizcore.facts.snapshot import build_snapshot
    from wizcore.llm.client import LLMClient, extract_json

    from graph.nodes import _slide_text, _timely_context
    from imaging import render as render_mod
    from prompts.library import post_system_prompt, post_user_prompt
    from validators import validate

    reader = SiteReader(
        repo=config.site_repo, token=config.site_read_token,
        ref=config.site_branch, local_dir=config.site_local_dir or None,
    )
    snapshot = build_snapshot(reader)
    facts = snapshot.to_prompt_block(include_testimonials=True)
    client = LLMClient(model=config.voice_model)

    results: list[dict] = []
    history: list[str] = []

    for index, (platform, pillar, fmt, slides) in enumerate(cases, 1):
        print(f"[{index}/{len(cases)}] {platform}/{pillar} ({fmt}) ...", flush=True)
        started = time.time()

        # A timely case needs a verified angle and its captured sources; without
        # them the grounding gate rejects it, correctly.
        angle_row, sources, extra = (None, [], "")
        if pillar == "timely":
            class _Slot:  # minimal shim; _timely_context only reads these two
                pass
            slot = _Slot()
            slot.pillar, slot.platform = "timely", platform
            angle_row, sources, extra = _timely_context(config, slot)
            if not angle_row:
                results.append({
                    "platform": platform, "pillar": pillar, "fmt": fmt,
                    "skipped": "no verified trend angle available right now",
                })
                continue

        attempts: list[dict] = []
        accepted = None
        note = ""
        for attempt in range(1, config.max_regenerations + 2):
            try:
                raw = client.complete(
                    system=post_system_prompt(facts),
                    user=post_user_prompt(pillar, platform, fmt, slides, extra + note),
                    max_tokens=2000, temperature=0.85,
                )
            except Exception as e:
                attempts.append({"attempt": attempt, "error": str(e)[:200]})
                break

            parsed = extract_json(raw)
            if not isinstance(parsed, dict):
                attempts.append({"attempt": attempt, "reasons": ["not a JSON object"]})
                note = "\n\nReturn only the JSON object."
                continue

            caption = str(parsed.get("caption") or "").strip()
            hashtags = [str(h) for h in (parsed.get("hashtags") or []) if str(h).strip()]
            slide_list = parsed.get("slides") or []
            image_count = (
                len(slide_list) if fmt == "carousel"
                else 0 if platform in ("threads", "x", "youtube") else 1
            )
            verdict = validate(
                caption=caption, hashtags=hashtags, image_count=image_count,
                platform_name=platform, snapshot=snapshot, history=history,
                slides_text=" ".join(_slide_text(s) for s in slide_list),
                repetition_threshold=config.repetition_threshold, sources=sources,
            )
            attempts.append({
                "attempt": attempt, "chars": len(caption),
                "reasons": verdict.reasons, "passed": verdict.ok,
            })
            if verdict.ok:
                accepted = {
                    "caption": caption, "hashtags": hashtags,
                    "slides": slide_list, "title": str(parsed.get("title") or ""),
                }
                history.append(caption)
                break
            note = (
                "\n\nThe previous draft was rejected:\n"
                + "\n".join(f"- {r}" for r in verdict.reasons)
                + "\nWrite a fresh version."
            )

        record = {
            "platform": platform, "pillar": pillar, "fmt": fmt,
            "attempts": attempts, "seconds": round(time.time() - started, 1),
            "angle": (angle_row or {}).get("headline"),
            "citation": (angle_row or {}).get("citation"),
            "sources": len(sources),
        }
        if not accepted:
            record["failed"] = "no draft passed the validators"
            results.append(record)
            continue

        record.update(accepted)
        record["images"] = _render(config, render_mod, accepted, platform, pillar, fmt, out_dir)
        results.append(record)

    return results


def _render(config, render_mod, draft: dict, platform: str, pillar: str,
            fmt: str, out_dir: Path) -> list[str]:
    """Render real images and copy them into the review folder."""
    from graph.nodes import _fallback_slide
    from platforms import Draft

    if platform in ("threads", "x", "youtube"):
        return []   # text-first; the agent renders nothing for these
    slides = draft["slides"] or [
        _fallback_slide(Draft(platform=platform, pillar=pillar,
                              caption=draft["caption"]))
    ]
    try:
        paths = render_mod.render_slides(slides, platform, f"{platform}_{pillar}")
    except Exception as e:
        print(f"    render failed: {e}")
        return []

    folder = out_dir / f"{platform}_{pillar}"
    folder.mkdir(parents=True, exist_ok=True)
    copied = []
    for path in paths:
        target = folder / Path(path).name
        shutil.copy2(path, target)
        copied.append(str(target.relative_to(out_dir)).replace("\\", "/"))
    return copied


def write_index(results: list[dict], out_dir: Path, config) -> None:
    """One page showing every post exactly as it would publish."""
    blocks = []
    for r in results:
        head = f"{r['platform']} · {r['pillar']} · {r['fmt']}"
        if r.get("skipped"):
            blocks.append(f"<section class='card skip'><h2>{html.escape(head)}</h2>"
                          f"<p class='muted'>skipped — {html.escape(r['skipped'])}</p></section>")
            continue
        if r.get("failed"):
            reasons = "".join(
                f"<li>{html.escape(str(x))}</li>"
                for a in r["attempts"] for x in a.get("reasons", [])
            )
            blocks.append(f"<section class='card fail'><h2>{html.escape(head)}</h2>"
                          f"<p class='muted'>rejected by validators</p><ul>{reasons}</ul></section>")
            continue

        imgs = "".join(
            f"<img src='{html.escape(p)}' alt='' loading='lazy'>" for p in r.get("images", [])
        )
        tags = " ".join(f"#{t.lstrip('#')}" for t in r.get("hashtags", []))
        tries = len(r["attempts"])
        retry_note = (
            f"<span class='pill warn'>{tries} attempts</span>" if tries > 1
            else "<span class='pill ok'>first try</span>"
        )
        cite = (
            f"<p class='cite'>Source (posted as first comment): "
            f"{html.escape(r['citation'] or '')}</p>" if r.get("citation") else ""
        )
        angle = (
            f"<p class='angle'>Trend angle: {html.escape(r['angle'])}</p>"
            if r.get("angle") else ""
        )
        blocks.append(f"""
<section class='card'>
  <h2>{html.escape(head)} {retry_note}
      <span class='pill'>{r.get('chars', len(r.get('caption','')))} chars</span></h2>
  {angle}
  <pre class='caption'>{html.escape(r.get('caption',''))}</pre>
  <p class='tags'>{html.escape(tags)}</p>
  {cite}
  <div class='shots'>{imgs}</div>
</section>""")

    passed = sum(1 for r in results if r.get("caption"))
    first_try = sum(1 for r in results if r.get("caption") and len(r["attempts"]) == 1)
    total_imgs = sum(len(r.get("images", [])) for r in results)

    (out_dir / "index.html").write_text(f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>WizCodes content review</title>
<style>
:root{{color-scheme:light dark;--bg:#fff;--fg:#101828;--muted:#667085;--line:#e4e7ec;--accent:#2E90C4}}
@media(prefers-color-scheme:dark){{:root{{--bg:#0b1220;--fg:#e6edf5;--muted:#9fb0c4;--line:#1e2a3a}}}}
*{{box-sizing:border-box}}
body{{margin:0;padding:32px;background:var(--bg);color:var(--fg);
 font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:1100px;margin-inline:auto}}
h1{{font-size:1.6rem;margin:0 0 4px}}
.sum{{color:var(--muted);margin-bottom:28px}}
.card{{border:1px solid var(--line);border-radius:14px;padding:20px;margin-bottom:22px}}
.card.fail{{border-color:#f97066}} .card.skip{{opacity:.6}}
h2{{font-size:1rem;margin:0 0 10px;letter-spacing:.02em;text-transform:uppercase;color:var(--accent)}}
.pill{{font-size:.7rem;background:var(--line);color:var(--muted);padding:2px 8px;border-radius:99px;
 text-transform:none;letter-spacing:0;margin-left:6px}}
.pill.ok{{background:#d1fadf;color:#05603a}} .pill.warn{{background:#fef0c7;color:#93370d}}
@media(prefers-color-scheme:dark){{.pill.ok{{background:#054f31;color:#a6f4c5}}.pill.warn{{background:#7a2e0e;color:#fedf89}}}}
.caption{{white-space:pre-wrap;font:inherit;margin:0 0 10px;background:transparent}}
.tags{{color:var(--accent);margin:0 0 6px;font-size:.9rem}}
.cite,.angle{{color:var(--muted);font-size:.85rem;margin:4px 0}}
.shots{{display:flex;gap:10px;overflow-x:auto;padding-top:10px}}
.shots img{{height:300px;border-radius:10px;border:1px solid var(--line);flex:0 0 auto}}
.muted{{color:var(--muted)}}
</style></head><body>
<h1>WizCodes — content review</h1>
<p class="sum">{datetime.now(ZoneInfo(config.display_tz)):%d %b %Y %H:%M} · {passed}/{len(results)} passed all four validators ·
{first_try} on the first attempt · {total_imgs} images rendered ·
model {html.escape(config.voice_model)} · <strong>nothing was published</strong></p>
{''.join(blocks)}
</body></html>""", encoding="utf-8")

    (out_dir / "results.json").write_text(
        json.dumps(results, indent=2, default=str), encoding="utf-8"
    )


def main() -> int:
    import dataclasses

    parser = argparse.ArgumentParser(description="Generate a content review set")
    parser.add_argument("--quick", action="store_true", help="one case per platform")
    parser.add_argument("--pillars", default="", help="comma-separated pillar filter")
    parser.add_argument("--platforms", default="", help="comma-separated platform filter")
    args = parser.parse_args()

    from wizcore.obs.log import setup_logging

    from config import AGENT_NAME, CONFIG

    # DRY_RUN is forced, not merely defaulted. This tool exists to be run
    # casually while reviewing copy, and a review that could publish is not a
    # review.
    config = dataclasses.replace(CONFIG, dry_run=True)
    setup_logging(AGENT_NAME, "showcase", "WARNING")

    cases = QUICK if args.quick else SWEEP
    if args.pillars:
        keep = {p.strip() for p in args.pillars.split(",")}
        cases = [c for c in cases if c[1] in keep]
    if args.platforms:
        keep = {p.strip() for p in args.platforms.split(",")}
        cases = [c for c in cases if c[0] in keep]
    if not cases:
        print("no cases match those filters", file=sys.stderr)
        return 2

    stamp = datetime.now(ZoneInfo(config.display_tz)).strftime("%Y%m%d_%H%M")
    out_dir = AGENT_ROOT / "output" / f"showcase_{stamp}"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating {len(cases)} post(s) -> {out_dir}\n")
    results = build(config, cases, out_dir)
    write_index(results, out_dir, config)

    passed = sum(1 for r in results if r.get("caption"))
    print(f"\n  {passed}/{len(results)} passed all validators")
    print(f"  open: {out_dir / 'index.html'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
